services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        value: srinivasulusachu2005@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RENDER
        value: TRUE
